M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu22.04.1 date 2026-09-16T00:50:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-16T00:50:50+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X7.0Y-7.0
X80.0Y-7.0
X96.0Y-83.0
M30
